export function generateNonce(): string {
	return crypto.randomUUID().replace(/-/g, "");
}

export function getSecurityHeaders(nonce: string): Record<string, string> {
	return {
		// https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html
		"Content-Security-Policy": [
			"base-uri 'self'",
			"default-src 'self'",
			"frame-ancestors 'none'",
			"img-src 'self' data:",
			"object-src 'none'",
			`script-src 'self' 'nonce-${nonce}'`,
		].join("; "),
		"Cross-Origin-Embedder-Policy": "require-corp",
		"Cross-Origin-Opener-Policy": "same-origin",
		"Cross-Origin-Resource-Policy": "same-site",
		"Permissions-Policy": [
			// https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md
			// https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Permissions-Policy#directives
			"accelerometer=()",
			"all-screens-capture=()",
			"ambient-light-sensor=()",
			// "aria-notify=()",
			"attribution-reporting=()",
			// "autofill=()",
			"autoplay=()",
			"battery=()",
			"bluetooth=()",
			"browsing-topics=()",
			"camera=()",
			"captured-surface-control=()",
			"ch-ua-arch=()",
			"ch-ua-bitness=()",
			"ch-ua-full-version-list=()",
			"ch-ua-full-version=()",
			"ch-ua-high-entropy-values=()",
			"ch-ua-mobile=()",
			"ch-ua-model=()",
			"ch-ua-platform-version=()",
			"ch-ua-platform=()",
			"ch-ua-wow64=()",
			"ch-ua=()",
			// "clipboard-read=()",
			// "clipboard-write=()",
			"compute-pressure=()",
			"cross-origin-isolated=()",
			"deferred-fetch-minimal=()",
			"deferred-fetch=()",
			"digital-credentials-create=()",
			"digital-credentials-get=()",
			"direct-sockets=()",
			"display-capture=()",
			"encrypted-media=()",
			"execution-while-not-rendered=()",
			"execution-while-out-of-viewport=()",
			"focus-without-user-activation=()",
			// "fullscreen=()",
			"gamepad=()",
			"geolocation=()",
			"gyroscope=()",
			"hid=()",
			"identity-credentials-get=()",
			"idle-detection=()",
			"join-ad-interest-group=()",
			"keyboard-map=()",
			"language-detector=()",
			"language-model=()",
			"local-fonts=()",
			"magnetometer=()",
			"manual-text=()",
			"mediasession=()",
			"microphone=()",
			"midi=()",
			"monetization=()",
			"navigation-override=()",
			"on-device-speech-recognition=()",
			"otp-credentials=()",
			"payment=()",
			// "picture-in-picture=()",
			"private-state-token-issuance=()",
			"private-state-token-redemption=()",
			// "publickey-credentials-create=()",
			// "publickey-credentials-get=()",
			"rewriter=()",
			"run-ad-auction=()",
			"screen-wake-lock=()",
			"serial=()",
			"smart-card=()",
			"speaker-selection=()",
			"storage-access=()",
			"summarizer=()",
			"sync-script=()",
			"sync-xhr=()",
			"translator=()",
			"trust-token-redemption=()",
			"unload=()",
			"usb=()",
			// "web-share=()",
			"vertical-scroll=()",
			"window-management=()",
			"writer=()",
			"xr-spatial-tracking=()",
		].join(", "),
		"Referrer-Policy": "strict-origin-when-cross-origin",
		"X-Content-Type-Options": "nosniff",
		"X-Frame-Options": "DENY",
		// "X-Robots-Tag": "noindex, nofollow"
	};
}
